# Generated by Django 3.1.2 on 2020-10-17 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processAuth', '0001_initial'),
        ('processCore', '0002_task_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='responsable',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='processAuth.usermodel'),
        ),
    ]
