# Generated by Django 3.1.2 on 2020-10-17 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processAuth', '0001_initial'),
        ('processCore', '0003_auto_20201017_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='responsable',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='processAuth.usermodel'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Terminada'), (1, 'En Proceso'), (2, 'Atrasada'), (3, 'Rechazado'), (4, 'Confirmacion')], default=4),
        ),
    ]
