# Generated by Django 3.1.3 on 2020-11-13 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processAuth', '0001_initial'),
        ('processCore', '0006_unidadinterna'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaSubordinada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Terminada'), (1, 'En Proceso'), (2, 'Atrasada'), (3, 'Rechazado'), (4, 'Confirmacion')], default=4)),
                ('responsable', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='processAuth.usermodel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processCore.task')),
            ],
        ),
    ]
